# permissions for end users to view schedulednotebooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schedulednotebook-viewer-role
rules:
- apiGroups:
  - papermill.papermill.dev
  resources:
  - schedulednotebooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - papermill.papermill.dev
  resources:
  - schedulednotebooks/status
  verbs:
  - get
